---

- hosts: "{{ STAKER_NODE }}"
  user: root
  strategy: free
  vars:
    - data: "{{ SETUP_HOME }}/{{ service }}/data"
    - service: ag-chain-cosmos
    - BOOTSTRAP_TOKENS: 100provisionpass
    - CHAIN_NAME: "{{ lookup('file', SETUP_HOME + '/ag-chain-cosmos/chain-name.txt') }}"
    - NETWORK_CONFIG_URL: https://testnet.agoric.com/network-config
    - FAUCET_TOKENS: "{{ lookup('file', SETUP_HOME + '/boot-tokens.txt') }}"
    - STAKER: ag-staker
    - STAKER_INIT_COINS: 62000000ubld
    - STAKER_SELF_DELEGATION: 50000000ubld
    - STAKER_NODE: validator0
  roles:
    - cosmos-genesis
