---

- hosts: all
  user: root
  gather_facts: no
  strategy: free
  vars:
    - PROM_NODE_EXPORTER_VERSION: 0.18.1
    - service: node-exporter
    - execline: /usr/local/sbin/node_exporter
    - chdir: /
    - user: root
  roles:
    - prometheus-prereq
    - install
    - stop
    - start
