---

- hosts: all
  user: root
  gather_facts: no
  strategy: free
  vars:
    - service: node-exporter
    - user: root
    - to_remove:
      - /etc/systemd/system/node-exporter.service
  roles:
    - stop
    - remove
