version: "2.2"
services:
  ag-solo:
    # This tag needs to be the SDK used by the $NETCONFIG_URL
    image: agoric/cosmic-swingset-solo:${SDK_TAG:-2.14.0}
    # ISSUE: 127.0.0.1? not a docker network?
    ports:
      - "${HOST_PORT:-8000}:${PORT:-8000}"
    volumes:
      - "ag-solo-state:/usr/src/app/solo"
      - "ag-solo-state:/data/solo"
      - "$HOME/.agoric:/root/.agoric"
    environment:
      - "AG_SOLO_BASEDIR=${SOLO_HOME:-agoric}"
    command:
      - setup
      - --webhost=0.0.0.0
      - --webport=${PORT:-8000}
      - --netconfig=${NETCONFIG_URL:-https://devnet.agoric.net/network-config}
volumes:
  ag-solo-state:
